const styles = {
  root: { display: "flex", height: "100vh", fontFamily: "'Georgia', 'Times New Roman', serif", background: "#f8f9fb", color: "#1a1a2e", overflow: "hidden" },
  sidebar: { background: "#0f172a", color: "#e2e8f0", transition: "width 0.3s", flexShrink: 0, display: "flex", flexDirection: "column" },
  sidebarInner: { width: 280, padding: 20, display: "flex", flexDirection: "column", gap: 12, minHeight: "100%" },
  sidebarHeader: { paddingBottom: 16, borderBottom: "1px solid rgba(255,255,255,0.1)", marginBottom: 4 },
  logoText: { display: "block", fontSize: 22, fontWeight: 800, color: "#60a5fa", letterSpacing: -0.5 },
  logoSub: { fontSize: 11, color: "#94a3b8", textTransform: "uppercase", letterSpacing: 1 },
  uploadBtn: { background: "#1e40af", color: "white", border: "none", borderRadius: 8, padding: "10px 14px", fontSize: 13, fontWeight: 600, cursor: "pointer", display: "flex", gap: 8, alignItems: "center" },
  catSection: { display: "flex", flexDirection: "column" },
  catHeader: { display: "flex", alignItems: "center", gap: 8, padding: "10px 12px", border: "none", color: "#e2e8f0", cursor: "pointer", borderRadius: 6, textAlign: "left", fontSize: 13, fontWeight: 600, transition: "all 0.2s" },
  catTitle: { flex: 1 },
  catOptions: { display: "flex", flexDirection: "column", gap: 4, paddingLeft: 12, marginTop: 4 },
  optionBtn: { background: "rgba(255,255,255,0.05)", color: "#cbd5e1", border: "1px solid rgba(255,255,255,0.08)", borderRadius: 6, padding: "8px 12px", fontSize: 12, cursor: "pointer", textAlign: "left", transition: "all 0.15s" },
  clearBtn: { marginTop: "auto", background: "transparent", color: "#ef4444", border: "1px solid #ef4444", borderRadius: 6, padding: "8px 14px", fontSize: 12, cursor: "pointer" },
  main: { flex: 1, display: "flex", flexDirection: "column", overflow: "hidden" },
  topbar: { background: "white", borderBottom: "1px solid #e5e7eb", padding: "12px 24px", display: "flex", alignItems: "center", gap: 16, flexShrink: 0 },
  menuBtn: { background: "none", border: "none", fontSize: 20, cursor: "pointer", color: "#374151", padding: "4px 8px" },
  topTitle: { fontSize: 17, fontWeight: 700, color: "#111827" },
  topSub: { fontSize: 12, color: "#9ca3af" },
  badge: { marginLeft: "auto", background: "#eff6ff", color: "#1d4ed8", padding: "4px 12px", borderRadius: 20, fontSize: 12, fontWeight: 600, flexShrink: 0 },
  chatArea: { flex: 1, overflow: "auto", padding: "24px 32px", display: "flex", flexDirection: "column", gap: 20 },
  empty: { margin: "auto", textAlign: "center", maxWidth: 520, padding: "40px 20px" },
  emptyIcon: { fontSize: 56, marginBottom: 16 },
  emptyTitle: { fontSize: 26, fontWeight: 800, color: "#111827", marginBottom: 12 },
  emptySub: { fontSize: 15, color: "#6b7280", lineHeight: 1.7, marginBottom: 32 },
  emptyCards: { display: "grid", gridTemplateColumns: "1fr 1fr", gap: 12 },
  emptyCard: { background: "white", border: "1px solid #e5e7eb", borderRadius: 10, padding: "16px 12px", display: "flex", flexDirection: "column", gap: 8, alignItems: "center", boxShadow: "0 1px 4px rgba(0,0,0,0.04)" },
  msgRow: { display: "flex", gap: 12, alignItems: "flex-end" },
  avatar: { width: 32, height: 32, borderRadius: "50%", background: "#eff6ff", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, flexShrink: 0 },
  userAvatar: { width: 32, height: 32, borderRadius: "50%", background: "#f3f4f6", display: "flex", alignItems: "center", justifyContent: "center", fontSize: 16, flexShrink: 0 },
  bubble: { borderRadius: 14, padding: "12px 16px", wordBreak: "break-word" },
  userBubble: { background: "#1d4ed8", color: "white", borderBottomRightRadius: 4 },
  botBubble: { background: "white", border: "1px solid #e5e7eb", borderBottomLeftRadius: 4, boxShadow: "0 1px 3px rgba(0,0,0,0.06)" },
  typing: { display: "flex", gap: 6, padding: "4px 0" },
  dot: { width: 7, height: 7, borderRadius: "50%", background: "#94a3b8", animation: "pulse 1.2s ease-in-out infinite", display: "inline-block" },
  inputBar: { padding: "16px 32px 20px", background: "white", borderTop: "1px solid #e5e7eb", flexShrink: 0 },
  inputWrap: { display: "flex", gap: 10, alignItems: "flex-end" },
  input: { flex: 1, padding: "12px 16px", border: "1px solid #d1d5db", borderRadius: 10, fontSize: 14, fontFamily: "inherit", resize: "none", outline: "none", lineHeight: 1.5 },
  sendBtn: { background: "#1d4ed8", color: "white", border: "none", borderRadius: 10, width: 44, height: 44, fontSize: 18, cursor: "pointer", flexShrink: 0, display: "flex", alignItems: "center", justifyContent: "center", transition: "opacity 0.2s" },
  hint: { fontSize: 11, color: "#9ca3af", marginTop: 6, textAlign: "center" },
  overlay: { position: "fixed", inset: 0, background: "rgba(0,0,0,0.55)", display: "flex", alignItems: "center", justifyContent: "center", zIndex: 100 },
  modal: { background: "white", borderRadius: 16, width: "90%", maxWidth: 540, maxHeight: "85vh", overflow: "auto", boxShadow: "0 25px 50px rgba(0,0,0,0.2)" },
  modalHeader: { padding: "20px 24px", borderBottom: "1px solid #e5e7eb", display: "flex", justifyContent: "space-between", alignItems: "center" },
  closeBtn: { background: "none", border: "none", fontSize: 20, cursor: "pointer", color: "#6b7280" },
  modalBody: { padding: 24, display: "flex", flexDirection: "column", gap: 16 },
  fileZone: { border: "2px dashed #d1d5db", borderRadius: 12, padding: "32px 24px", display: "flex", flexDirection: "column", alignItems: "center", gap: 8, cursor: "pointer", background: "#f9fafb" },
  orDivider: { textAlign: "center", color: "#9ca3af", fontSize: 13, fontWeight: 600 },
  pasteArea: { width: "100%", padding: 12, border: "1px solid #d1d5db", borderRadius: 8, fontSize: 13, fontFamily: "inherit", resize: "vertical", outline: "none", boxSizing: "border-box" },
  modalActions: { display: "flex", justifyContent: "flex-end", gap: 10 },
  cancelBtn: { padding: "10px 20px", border: "1px solid #d1d5db", borderRadius: 8, background: "white", cursor: "pointer", fontSize: 13 },
  analyzeBtn: { padding: "10px 20px", background: "#1d4ed8", color: "white", border: "none", borderRadius: 8, cursor: "pointer", fontSize: 13, fontWeight: 600 },
  card: { display: "flex", flexDirection: "column", gap: 14 },
  cardHeader: { display: "flex", justifyContent: "space-between", alignItems: "center", gap: 8 },
  cardPolicy: { fontWeight: 700, fontSize: 15, color: "#111827" },
  readingBadge: { background: "#f3f4f6", color: "#6b7280", padding: "2px 10px", borderRadius: 20, fontSize: 11, fontWeight: 600, flexShrink: 0 },
  cardSummary: { fontSize: 14, lineHeight: 1.7, color: "#374151", background: "#f8fafc", padding: "12px 14px", borderRadius: 8, margin: 0 },
  section: { background: "#fafafa", padding: "12px 14px", borderRadius: 8 },
  fbRow: { display: "flex", alignItems: "center", gap: 8, paddingTop: 8, borderTop: "1px solid #f0f0f0" },
  fbBtn: { border: "none", cursor: "pointer", fontSize: 18, padding: "2px 6px", borderRadius: 6 },
  audioBar: { display: "flex", alignItems: "center", gap: 10, background: "#f0f9ff", border: "1px solid #bae6fd", borderRadius: 10, padding: "10px 14px", flexWrap: "wrap" },
  audioLabel: { fontSize: 13, fontWeight: 600, color: "#0369a1", flex: 1 },
  audioControls: { display: "flex", gap: 8 },
  audioBtn: { border: "none", borderRadius: 8, padding: "6px 14px", fontSize: 12, fontWeight: 700, cursor: "pointer", transition: "all 0.2s" },
  waveWrap: { display: "flex", alignItems: "center", gap: 3, height: 20 },
  wave: { width: 3, background: "#0ea5e9", borderRadius: 4, animation: "wave 0.8s ease-in-out infinite alternate" },
  copyright: { marginTop: "auto", paddingTop: 16, borderTop: "1px solid rgba(255,255,255,0.08)", fontSize: 12, color: "#475569", textAlign: "center" },
  processingBox: { display: "flex", flexDirection: "column", alignItems: "center", gap: 12, padding: "40px 24px", textAlign: "center" },
  spinnerWrap: { width: 48, height: 48, display: "flex", alignItems: "center", justifyContent: "center" },
  spinner: { width: 36, height: 36, border: "4px solid #e5e7eb", borderTop: "4px solid #1d4ed8", borderRadius: "50%", animation: "spin 0.8s linear infinite" },
};

export default styles;
